### ISSUE TITLE
Metabase Athena connections not working after new update

### ISSUE THREAD

**Issue by lhgrigio** [metabase/metabase#63396]
### Describe the bug

HI team!

I could not find this bug reported anywhere, this issue appears to only affect the Metabase service in ECS.
Our Athena connections apparently stopped working after a new update yesterday, this error is displayed in the connection:
```
Connection test failed: Could not get query execution ID: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)
``` 

Is this something that will be fixed by the SDK update seen at https://github.com/metabase/metabase/pull/63369 ?

Thank you in advance, if any additional information is needed please let me know!

### To Reproduce

1. In an ECS deployed environment, Go to Admin Settings
2. Click on Databases
3. See error on every Athena connection

### Logs

[logs.txt](https://github.com/user-attachments/files/22279834/logs.txt)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "bigquery-cloud-sdk",
      "athena"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-09-10",
      "tag": "v0.56.5",
      "hash": "3dab72a"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.336-256.559.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

High, it's blocking access to Athena connections

**Comment by ericcj** [comment]
We are experiencing the same problem after upgrading from 0.55.5 to 0.56.5 but seemed to have some problems (maybe with a duplicate index?) rolling back to the old version so could you let us know if there is an imminent fix to roll forward?

The full stack trace is 

```
[16e92ffc-36e0-4c5b-b999-af9abbfccce6] 2025-09-12T10:47:21-04:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Could not get query execution ID: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)
{:database_id 13,
 :parameterized false,
 :started_at #t "2025-09-12T14:47:21.325153033Z[GMT]",
 :via
 [{:status :failed,
   :class java.lang.NoClassDefFoundError,
   :error "Could not initialize class io.netty.buffer.ByteBufAllocator",
   :stacktrace
   ["io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:60)"
    "io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:75)"
    "io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:30)"
    "io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:336)"
    "io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:164)"
    "io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:125)"
    "io.netty.channel.pool.SimpleChannelPool.connectChannel(SimpleChannelPool.java:267)"
    "io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:177)"
    "io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:162)"
    "io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:157)"
    "software.amazon.awssdk.http.nio.netty.internal.HonorCloseOnReleaseChannelPool.acquire(HonorCloseOnReleaseChannelPool.java:45)"
    "software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.initializeProtocol(HttpOrHttp2ChannelPool.java:109)"
    "software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.acquire0(HttpOrHttp2ChannelPool.java:91)"
    "software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.lambda$acquire$0(HttpOrHttp2ChannelPool.java:76)"
    "software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.lambda$doInEventLoop$3(NettyUtils.java:283)"
    "io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)"
    "io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)"
    "io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148)"
    "io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:141)"
    "io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:507)"
    "io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)"
    "io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073)"
    "io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)"
    "java.base/java.lang.Thread.run(Unknown Source)"
    nil]}
  {:status :failed,
   :class software.amazon.awssdk.core.exception.SdkClientException,
   :error
   "Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)",
   :stacktrace
   ["software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:130)"
    "software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:95)"
    "software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.retryPolicyDisallowedRetryException(RetryableStageHelper.java:168)"
    "software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:139)"
    "software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:157)"
    "software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:117)"
    "java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)"
    "java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)"
    "java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)"
    "java.base/java.util.concurrent.CompletableFu...
```

only athena mention in the changelog doesn't seem related https://github.com/metabase/metabase/pull/61934 and no mentions of jdk/aws

but seems most likely this was broken in 0.56.3 by https://github.com/metabase/metabase/pull/62480

most similar issue i found is someone with both netty-buffer and netty-all jars in their classpath https://stackoverflow.com/questions/51022663/noclassdeffounderror-for-io-netty-buffer-pooledbytebufallocator

**Comment by ericcj** [comment]
I confirmed that reverting to 0.56.2 fixes the problem

**Comment by lhgrigio** [comment]
@ericcj Quick question, did you had to downgrade the DB as well or just changing the running version for Metabase worked with the same db structure?

**Comment by ericcj** [comment]
the same metabase db worked fine for 0.56.2 as 0.56.5 but i don't think it worked when i attempted to roll back to 0.55.5

**Comment by lhgrigio** [comment]
Just confirmed that downgrading 0.56.2 solved the problem for me as well.
@ericcj you are a hero, thank you for pointing me to the correct version!

**Comment by dpsutton** [comment]
```diff
❯ git diff v0.56.2..v0.56.5 -- modules/drivers/athena/deps.edn
diff --git a/modules/drivers/athena/deps.edn b/modules/drivers/athena/deps.edn
index 117df917e86..62edf8dc5b6 100644
--- a/modules/drivers/athena/deps.edn
+++ b/modules/drivers/athena/deps.edn
@@ -9,4 +9,4 @@
  ;; https://github.com/metabase/metabase/actions/workflows/athena.yml
  ;; new versions of athena-jdbc appear here:
  ;; https://docs.aws.amazon.com/athena/latest/ug/jdbc-v3-driver.html#jdbc-v3-driver-download-uber-jar
- {com.metabase/athena-jdbc {:mvn/version "3.5.0"}}}
+ {com.metabase/athena-jdbc {:mvn/version "3.5.1"}}}
```

**Comment by vprus** [comment]
I have the same problem with Metabase self-built from 0.56.6 tag (which appears to have the 3.6.0 version of the Athena driver)

**Comment by dragonsahead** [comment]
@vprus we can't debug self built instances unfortunately. I'll test right now myself

**Comment by dragonsahead** [comment]
Hey @lhgrigio @ericcj, this only happens if you're using roles attached to the ECS task in AWS correct?

**Comment by vprus** [comment]
> [@vprus](https://github.com/vprus) we can't debug self built instances unfortunately. I'll test right now myself

@paoliniluis : FWIW, I solved my problem by downgrading and not asking for help. I'm just adding context that might be helpful - in particular that version 5.6.6 (with 3.6.0 of the driver) does not appear to solve the issue. If that helps, we're using AWS EKS and IAM roles for service accounts.

**Comment by dragonsahead** [comment]
I just did the following:
- created a new EC2 instance with coretto 21 and metabase v1.56.6
- added a role to the instance that can connect to athena

I was able to connect without any issues

can someone help me here?

**Comment by vprus** [comment]
I have just tried with the official images, like so: 
```
image:
  repository: metabase/metabase
  tag: v0.56.6.x
```
and see the same issue:
```
2025-09-23 11:14:01,454 ERROR models.database :: Health check: failure with error Production: Athena {:id 32 :reason exception :message Connection test failed: Could not get query execution ID: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)}
java.sql.SQLException: Connection test failed: Could not get query execution ID: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)
        at com.amazon.athena.jdbc.AthenaConnection.testConnection(AthenaConnection.java:440)
        at com.amazon.athena.jdbc.AthenaDriver.connect(AthenaDriver.java:135)
        at metabase.plugins.jdbc_proxy$proxy_driver$reify__98731.connect(jdbc_proxy.clj:37)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:368)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:365)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__95748.invoke(connection.clj:377)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__95730.invoke(connection.clj:353)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invokeStatic(ssh_tunnel.clj:152)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invoke(ssh_tunnel.clj:141)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:348)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:344)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:376)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:372)
        at metabase.driver.sql_jdbc$fn__97988.invokeStatic(sql_jdbc.clj:52)
        at metabase.driver.sql_jdbc$fn__97988.invoke(sql_jdbc.clj:50)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.warehouses.models.database$health_check_database_BANG_$fn__70189$fn__70190.invoke(database.clj:210)
        at clojure.core$binding_conveyor_fn$fn__5844.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Could not get query execution ID: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)
        at com.amazon.athena.jdbc.AthenaStatementBase.getQueryExecutionId(AthenaStatementBase.java:185)
        at com.amazon.athena.jdbc.AthenaStatement.getQueryExecutionId(AthenaStatement.java:7)
        at com.amazon.athena.jdbc.AthenaStatementBase.runQuery(AthenaStatementBase.java:136)
        at com.amazon.athena.jdbc.AthenaStatement.execute(AthenaStatement.java:14)
        at com.amazon.athena.jdbc.AthenaConnection.testConnection(AthenaConnection.java:438)
        ... 34 more
        Suppressed: java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)
                at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
                at com.amazon.athena.jdbc.AthenaStatementBase.getQueryExecutionId(AthenaStatementBase.java:179)
                ... 38 more
        Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)
                at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:130)
                at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:95)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.retryPolicyDisallowedRetryException(RetryableStageHelper.java:168)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:139)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:157)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:117)
                at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
                at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:78)
                at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$execute$0(MakeAsyncHttpRequestStage.java:108)
                at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:255)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:167)
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
                at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
                ... 3 more
        Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.buffer.ByteBufAllocator
                at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:60)
                at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:75)
                at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:30)
                at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:336)
                at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:164)
                at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:125)
                at io.netty.channel.pool.SimpleChannelPool.connectChannel(SimpleChannelPool.java:267)
                at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:177)
                at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:162)
                at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:157)
                at software.amazon.awssdk.http.nio.netty.internal.HonorCloseOnReleaseChannelPool.acquire(HonorCloseOnReleaseChannelPool.java:45)
                at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.initializeProtocol(HttpOrHttp2ChannelPool.java:109)
                at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.acquire0(HttpOrHttp2ChannelPool.java:91)
                at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.lambda$acquire$0(HttpOrHttp2ChannelPool.java:76)
                at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.lambda$doInEventLoop$3(NettyUtils.java:283)
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
                at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:141)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:507)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                ... 1 more
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: io/netty/util/internal/AtomicReferenceCountUpdater [in thread "aws-java-sdk-NettyEventLoop-1-1"]
                at java.base/java.lang.ClassLoader.defineClass1(Native Method)
                at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
                at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
                at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
                at java.base/java.net.URLClassLoader$1.run(Unknown Source)
                at java.base/java.net.URLClassLoader$1.run(Unknown Source)
                at java.base/java.security.AccessController.doPrivileged(Unknown Source)
                at java.base/java.net.URLClassLoader.findClass(Unknown Source)
                at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
                at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
                at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
                at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
                at io.netty.buffer.AdaptivePoolingAllocator$Magazine.<clinit>(AdaptivePoolingAllocator.java:814)
                at io.netty.buffer.AdaptivePoolingAllocator$MagazineGroup.<init>(AdaptivePoolingAllocator.java:386)
                at io.netty.buffer.AdaptivePoolingAllocator.createMagazineGroupSizeClasses(AdaptivePoolingAllocator.java:219)
                at io.netty.buffer.AdaptivePoolingAllocator.<init>(AdaptivePoolingAllocator.java:190)
                at io.netty.buffer.AdaptiveByteBufAllocator.<init>(AdaptiveByteBufAllocator.java:56)
                at io.netty.buffer.AdaptiveByteBufAllocator.<init>(AdaptiveByteBufAllocator.java:51)
                at io.netty.buffer.AdaptiveByteBufAllocator.<init>(AdaptiveByteBufAllocator.java:47)
                at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:90)
                at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24)
                at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:60)
                at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:75)
                at io.netty.channel.socket.DefaultSocketChannelConfig.<init>(DefaultSocketChannelConfig.java:47)
                at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.<init>(NioSocketChannel.java:476)
                at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.<init>(NioSocketChannel.java:473)
                at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:113)
                at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:102)
                at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:95)
                at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:88)
                at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:81)
                at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:326)
                ... 20 more
Caused by: [CIRCULAR REFERENCE: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Could not initialize class io.netty.buffer.ByteBufAllocator (SDK Attempt Count: 1)]
```

**Comment by vprus** [comment]
Running 
```
jar -tf athena.metabase-driver.jar | grep AtomicReferenceCountUpdater
```
results in no output, so seems like this class is indeed lost during packaging.

**Comment by dragonsahead** [comment]
@vprus it wasn't there either in 56.2 

<img width="1177" height="767" alt="Image" src="https://github.com/user-attachments/assets/8dbc9954-25d5-4254-98cf-7017dc983bb3" />

**Comment by vprus** [comment]
That file was only added to netty on Jul 18 - https://github.com/netty/netty/commit/daab644ac00dea1f802fa0940ff22adb9b389316

That is Netty 4.2.4 and above. Probably 56.2 is using netty < 4.2.4?

**Comment by vprus** [comment]
I see updates to Netty 4.2.4, but in a different driver - though it's a driver we also use.
```
% git diff v0.56.2..v0.56.6 -- modules/drivers/bigquery-cloud-sdk/deps.edn
diff --git a/modules/drivers/bigquery-cloud-sdk/deps.edn b/modules/drivers/bigquery-cloud-sdk/deps.edn
index 2d3a0eafdaa..4efade78dc7 100644
--- a/modules/drivers/bigquery-cloud-sdk/deps.edn
+++ b/modules/drivers/bigquery-cloud-sdk/deps.edn
@@ -10,5 +10,10 @@
                                                         ;; netty is updated because of CVE
                                                         io.netty/netty-common
                                                         io.netty/netty-buffer]}
-  io.netty/netty-common                  {:mvn/version "4.2.2.Final"}
-  io.netty/netty-buffer                  {:mvn/version "4.2.1.Final"}}}
+  ;; pin arrow formats to 17 for cve about parquet files
+  org.apache.arrow/arrow-format          {:mvn/version "17.0.0"}
+  org.apache.arrow/arrow-memory-core     {:mvn/version "17.0.0"}
+  org.apache.arrow/arrow-memory-netty    {:mvn/version "17.0.0"}
+  org.apache.arrow/arrow-vector          {:mvn/version "17.0.0"}
+  io.netty/netty-common                  {:mvn/version "4.2.3.Final"}
+  io.netty/netty-buffer                  {:mvn/version "4.2.4.Final"}}}
```

I also note that netty-common and netty-buffer appear to be of different versions, maybe that's the root cause?

**Comment by dragonsahead** [comment]
latest 56.6 uses netty 4.2.4

<img width="902" height="275" alt="Image" src="https://github.com/user-attachments/assets/1ab99a49-1681-4ebc-b487-5014d0de930e" />

**Comment by vprus** [comment]
Yes, so
- Latest 56.6 uses netty 4.2.4, fails to load a class introduced in netty 4.2.4, and that class is physically missing in the jar.
- 56.2 used previous netty (which did not have that class) and works

I don't understand the build/package process at all, but it seems that parts of netty 4.2.4 got lost somehow.

**Comment by dragonsahead** [comment]
@vprus can you try using 56.6 but adding the old athena driver?

**Comment by vprus** [comment]
@paoliniluis : I don't know how :-(

The drivers under /plugins appear to be unpacked from the main metabase jar, so even if I put the old driver in the docker image, it is overwritten. And if I modify driver inside the K8S pod, it has no effect because metabase is already running.

**Comment by lhgrigio** [comment]
> Hey [@lhgrigio](https://github.com/lhgrigio) [@ericcj](https://github.com/ericcj), this only happens if you're using roles attached to the ECS task in AWS correct?

Hi @paoliniluis, we also tried using Key/Secret directly and it didn't solve the issue

**Comment by ericcj** [comment]
i can confirm it is working in 0.56.8

**Comment by dpsutton** [comment]
thank you for confirming! that is very helpful. Will upgrade the athena driver to 3.6.0 to bump some deps shortly to resolve some CVEs. But just wanted to get a known working version back up and running.
