### PR TITLE
Allow empty column aliases

### LINKED ISSUE #57685: Empty column Names break the SQL Editor
### Describe the bug

This is bad practice but if you alias a column to an empty string the Editor breaks

### To Reproduce

1. Go to New -> SQL Question -> `Select id AS "" from orders` -> Run:

Image

### Expected behavior

The UI doesn't break like that or at least you get a warning that empty column names aren't supported. In previous versions it used to work:

Image

### Logs

Image

```
console.js:13 Error
    at index.mjs:218:15
    at index.mjs:246:1
    at Array.map (<anonymous>)
    at t (index.mjs:2884:27)
    at index.mjs:2891:14
    at Object.getAllColumns (index.mjs:124:14)
    at index.mjs:2904:42
    at Object.getAllLeafColumns (index.mjs:116:21)
    at index.mjs:1514:97
    at index.mjs:1509:26
d.error	@	console.js:13
XMLHttpRequest.send		
(anonymous)	@	api.js:257
_makeRequestWithXhr	@	api.js:215
_makeRequest	@	api.js:210
_makeRequestWithRetries	@	api.js:182
(anonymous)	@	api.js:158
(anonymous)	@	services.js:117
g	@	services.js:130
(anonymous)	@	querying.ts:155
(anonymous)	@	querying.ts:296
(anonymous)	@	NativeQueryEditor.tsx:443

```

### Information about your Metabase installation

```JSON
54 cannot replicate on version 53
```

### Severity

Cosmetic since I doubt many users would be doing this but good to flag

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/57685

### Description

Allows empty column aliases. Follow up to https://github.com/metabase/metabase/pull/58621

### How to verify

1. See steps in original issue.
2. You should be able to see the query results
3. Save it as a question
4. Go to the question and then click "Explore results"
5. You should still be able to see the results

### Demo

todo

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: frontend/src/metabase/data-grid/constants.ts [hunk 1]
```diff
@@ -11,3 +11,4 @@ export const FOOTER_HEIGHT = 30;
 export const PINNED_BORDER_SEPARATOR_WIDTH = 3;
 export const DATASET_INDEX_ATTRIBUTE_NAME = "data-dataset-index";
 export const VIRTUAL_INDEX_ATTRIBUTE_NAME = "data-index";
+export const FALLBACK_ID_FOR_EMPTY_COLUMN_NAME = "\0_EMPTY_COLUMN_ID";
```
Comment (metamben) [inline frontend/src/metabase/data-grid/constants.ts:14]: is the pattern `"\0_OUR_ID"` something we use in other places to generate "private" IDs?

Comment (rileythomp) [reply frontend/src/metabase/data-grid/constants.ts:14]: I think so, it's used above in ``export const ROW_ID_COLUMN_ID = `\0_INDEX`;``. I just copied the FE changes from @romeovs original PR: https://github.com/metabase/metabase/pull/58621

**Review by romeovs — APPROVED** [review]
FE changes look ok, but please add an e2e assertion for [this comment](https://github.com/metabase/metabase/pull/58621#discussion_r2120497321) on my original fix attempt.

**Review by metamben — APPROVED** [review]
