### ISSUE TITLE
embedding-sdk-react 0.63.0: TypeScript definitions do not include CollectionBrowser `showDashboardQuestions` prop

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#78197]
## Describe the bug

#77941 (fixing #77905) added a `showDashboardQuestions` prop to the `CollectionBrowser` component, and the backport #78033 shipped in Metabase v1.63.1.1. However, the `@metabase/embedding-sdk-react` npm package `0.63.0` was published on 2026-07-16, before #77941 merged on 2026-07-17, so the package's bundled TypeScript definitions (`dist/index.d.ts`) do not include the new prop — the string `showDashboardQuestions` does not appear anywhere in the published `dist/`.

As a result, a TypeScript app that passes `showDashboardQuestions` to `CollectionBrowser` fails to compile, even when the connected Metabase instance is v1.63.1.1+ whose SDK bundle supports the prop at runtime.

## To Reproduce

Instance setup:

1. Metabase v1.63.1.2 EE with SDK embedding enabled (any v1.63.1.1+ instance).

Failure steps:

1. In a React + TypeScript app, `npm install @metabase/embedding-sdk-react@0.63.0`.
2. Render `<CollectionBrowser collectionId="root" showDashboardQuestions={false} />`.
3. Run `tsc --noEmit` (or any typechecking build).
4. See the TS2322 error below.

## Expected behavior

The published npm package's TypeScript definitions include every prop the same-major SDK bundle supports, so `showDashboardQuestions` compiles on `0.63.x`.

## Logs

```
src/App.tsx(20,11): error TS2322: Type '{ collectionId: "root"; showDashboardQuestions: boolean; }' is not assignable to type 'IntrinsicAttributes & { collectionId?: SdkCollectionId | undefined; pageSize?: number | undefined; visibleEntityTypes?: ("collection" | "dashboard" | "question" | "model")[] | undefined; visibleColumns?: CollectionBrowserListColumns[] | undefined; EmptyContentComponent?: ComponentType | ... 1 more ... | undefined; o...'.
  Property 'showDashboardQuestions' does not exist on type 'IntrinsicAttributes & { collectionId?: SdkCollectionId | undefined; pageSize?: number | undefined; visibleEntityTypes?: ("collection" | "dashboard" | "question" | "model")[] | undefined; visibleColumns?: CollectionBrowserListColumns[] | undefined; EmptyContentComponent?: ComponentType | ... 1 more ... | undefined; o...'.
```

## Information about your Metabase installation

Metabase v1.63.1.2 (EE), Docker. SDK: `@metabase/embedding-sdk-react@0.63.0` (published 2026-07-16T18:27Z), React 18.3.1, TypeScript 5.6.3.

## Severity

Blocks TypeScript SDK users from adopting the #77905 fix: the build fails with the prop, and without the prop dashboard questions still show (the runtime default is `true`). Workaround is suppressing the error (`// @ts-expect-error`) until an npm version with updated types is published — verified working against a v1.63.1.2 instance.

## Additional context

- Verified at tag `v0.63.1.2`: `frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.tsx` exports `showDashboardQuestions?: boolean` in `CollectionBrowserProps` (default `true`), and the component's prop schema accepts it — so the instance-served bundle honors the prop; only the npm type surface lags.
- Related: #77905 (original bug), #77941 (fix), #78033 (backport to 0.63.x).

**Comment by lorem--ipsum** [comment]
Just released 0.63.1 with the types.
