### ISSUE TITLE
Cannot send test email

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12275]
**Describe the bug**
Cannot send test email. The button changes to "Sending...", but nothing happens.

**To Reproduce**
1. Go to Admin > Settings > Email
2. (fill out email settings - doesn't matter if it is correct or not - Save)
3. Click "Send test email" - the button changes to "Sending...", but nothing happens beyond that.
4. The browser console says `TypeError: r._form.setFormErrors is not a function`, but there's no request to `/api/email/test`, so no success/error message either.

**Information about your Metabase Installation:**
Metabase 0.35.1, various backends and browsers.

**Additional context**
This used to work on 0.34.3 - it would send the request and display a message, in case of error, something like `Sorry, something went wrong. Please try again.` (real error is in the logs, but that's covered by #1692)

**Comment by flamber** [comment]
Fixed by #12283
