### ISSUE TITLE
Map drawing search does not work in 0.33.0

### ISSUE THREAD

**Issue by gdippolito** [metabase/metabase#10746]
**Describe the bug**

Drawing a map in the map view does not create a filter. 

**Logs**
```
app-main.bundle.js?a43410d9fdb01c3119b9:5 Uncaught TypeError: s is not a function
    at t.a.onFilter (app-main.bundle.js?a43410d9fdb01c3119b9:5)
    at t.fire (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at t._fireCreatedEvent (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at t._fireCreatedEvent (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at t._onMouseUp (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at t._onMouseUp (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at o (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at Ye (vendor.bundle.js?a43410d9fdb01c3119b9:1)
    at HTMLDocument.s [as _leaflet_touchendtouchend8232_22060] (vendor.bundle.js?a43410d9fdb01c3119b9:1)

```
**To Reproduce**
1. Go to a vistulization map with GPS coordinates plotted in the map
2. Click on "draw search"
3. Create a filter
4. Nothing happen

**Expected behavior**
The map should be filter for GPS coordinates 

**Information about your Metabase Installation:**
Chromium 76.0.3809.100
Linux Ubuntu
Postgres 11 (RDS)
Metabase 0.33.0
Custom installation
Metabase internal database postgres

**Severity**
Blocking some functionality that prevent us to adopt the tool entirely.

**Comment by gdippolito** [comment]
@flamber Yes I have seen this comment but the Github issue was referring to an old version of metabase. 
I thought it would be clearer to create a new issue specific to this version of the codebase. 

With 0.32.10 I did not experienced it so it is probably a regression introduced recently.

**Comment by mazameli** [comment]
I think I'm just going to go ahead and close this as a duplicate of #9314, which I've updated in priority.
