### ISSUE TITLE
Metabase showing the error `e.sent.map is not a function` after updating to v0.41.5

### ISSUE THREAD

**Issue by rohetoric** [metabase/metabase#19456]
**Describe the bug**
After updating metabase, to the version - v0.41.5, we are receiving the error - `e.sent.map is not a function`

**Logs**
styles.bundle.js

```
Uncaught ReferenceError: webpackJsonp is not defined
    <anonymous> https://vision.verloop.io/app/dist/styles.bundle.js?fd5b4582c89a44a792fa:1
```

app-main.bundle.js

```
Request entities,search_list,{"collection":"root"},fetch failed: TypeError: e.sent.map is not a function
```

    

**To Reproduce**
1. Update the version to v0.41.5 with the 
2. See the error `e.sent.map is not a function` on the screen

**Expected behavior**

**Screenshots**

![e.sent.map is not a function](https://user-images.githubusercontent.com/39988015/147065379-ed4a647b-d25a-471f-8c99-297a6b9240a8.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-16",
      "tag": "v0.41.5",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

- Your browser and the version: Firefox 95.0 (64 bit)
- Your operating system: Ubuntu 18.04
- Your databases: MySQL, Postgres, MongoDB
- Metabase version: v0.41.5
- Metabase hosting environment: GCP
- Metabase internal database:  H2 (default)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
We can't see anything on the screen, so it is a severe issue.

**Additional context**
We updated the metabase version from v0.35.4 to v0.41.5

**Comment by flamber** [comment]
Hi @rohetoric 
You have a cache somewhere, because I can see from the blue navigation bar that it's still showing the old version.
I don't know if it is some GCP reverse-proxy or feature, but you need to flush the cache.
It could also be some problem in your browser.

**Comment by rohetoric** [comment]
The issue still persists @flamber !
I cleared the cache of my browser as well as updated my Firefox to 95.0. I tried it on Chromium as well.
Can you please tell me a stable browser with Linux (Ubuntu preferably) environment where it has worked before?

**Comment by flamber** [comment]
@rohetoric The navigation bar should look like this - notice that there's no "Browse Data" on the official 0.41.5 release:
![image](https://user-images.githubusercontent.com/1447303/147242595-e1d3da99-5418-4e6a-b3bb-f89d15788531.png)

You have a reverse-proxy somewhere that is causing problems - disable or remove those:
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
