### PR TITLE
Fix Pie chart visualization error when rows contain nils

### LINKED ISSUE #13626: Pie chart shows spinner, when returned measure/value is `null` or `0`
**Describe the bug**
When a Pie visualization returns `null` or `0` (zero) as the measure/value for all the dimensions, then it causes loading-spinner on dashboard, or overlay with inaccessible error in question.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Custom Column formula `case([ID] = 2, 0, [Discount])` as "NewDiscount"
3. Filter by "ID" is `1, 2, 3`
4. Summarize "Sum of NewDiscount" grouped by "ID"
image
5. Change visualization to Pie and save as "Q1"
6. Add "Q1" to dashboard, add filter ID and connect to Order.ID and save dashboard
7. Input `1` or `2` in filter causes loading spinner - and the browser console is full of errors - and then changing the filter to `3`, without doing a browser refresh first, will then cause some funky looking breakage.
image
8. Going to question "Q1" and adding another filter "ID"=`1` will cause overlay on top of the error
image

**Expected behavior**
More like 0.36.8, but perhaps with dimensions still shown with zero value?
Doing first part of step 7, or step 8 on 0.36.8 will just show a gray circle without any other details.
image

**Information about your Metabase Installation:**
Metabase 0.37.0.2

**Additional context**
Related to #12586 and #12600
While it's related to #13571, it wasn't fixed by #13596.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes  #13626

I think it's a little worrisome that if a single visualization fails to render the entire Dashboard will fail to render -- why not just show an error in the component that fails and render the rest? I'm not sure how to fix that behavior at this point.

### CODE REVIEW

**Review by ohld — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@camsaul is it ok if I update the test with positive assertions directly in this PR before you merge it?

**Review by paulrosenzweig — APPROVED** [review]
LGTM

**Comment by nemanjaglumac** [comment]
> LGTM

The main Cypress test for this case failed (https://app.circleci.com/pipelines/github/metabase/metabase/10200/workflows/d7a243cf-41c1-4337-bfa7-e56992dd144a/jobs/361490). I didn't see it until now. It was working locally, and it's good chance it will work on Cypress `v5.5.0`, but I can't guarantee.

@camsaul if it's urgent to merge this, feel free to skip this test (if I don't figure out what's going on with it in the meantime).

**Comment by nemanjaglumac** [comment]
Since I cannot view the details or the video of this test failing, I spun up a local dev environment to try to replicate and see what's going on. Here are my findings (I'll post them in separate comments):

#### With no value set to the filter
1. Going to the dashboard from `/collection/root` results in data failing to load (it loads on mouse hover)
https://share.getcloudapp.com/NQu1PbvN (GIF screenshot)

There's all kinds of console warnings and errors
```
Uncaught Invariant Violation: findDOMNode was called on an unmounted component.
    at invariant (http://localhost:8080/app/dist/vendor.hot.bundle.js?5b5e02b9818d518b76f2:84935:15)
    at Object.findDOMNode (http://localhost:8080/app/dist/vendor.hot.bundle.js?5b5e02b9818d518b76f2:194157:21)
    at _class._getElement (http://localhost:8080/app/dist/app-main.hot.bundle.js?5b5e02b9818d518b76f2:46931:44)
    at _class.<anonymous> (http://localhost:8080/app/dist/vendor.hot.bundle.js?5b5e02b9818d518b76f2:198578:37)
    at _this._updateSize (http://localhost:8080/app/dist/app-main.hot.bundle.js?5b5e02b9818d518b76f2:46909:31)
```

Cannot read property of rows/slice/cols of undefined. (The same warning for each - don't want to repeat 3 logs)
```
settings.js:160 Error getting setting pie._metricIndex TypeError: Cannot read property 'cols' of undefined
    at Object.getValue (PieChart.jsx:157)
    at getComputedSetting (settings.js:141)
    at getComputedSettings (settings.js:99)
    at getComputedSettingsForSeries (visualization.js:89)
    at Visualization.transform (Visualization.jsx:233)
    at Visualization.componentWillMount (Visualization.jsx:166)
    at ReactCompositeComponent.js:345
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:344)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
```

**Comment by nemanjaglumac** [comment]
#### 2. When you set the filter value manually, values in a card/chart don't load, but the URL updates:
https://share.getcloudapp.com/JrugJve1 (GIF screenshot)

There are the same console errors in the console as for `#1`

#### 3. If you set the filter value directly through URL `/dashboard/1?id=1`, values in a card/chart eventually load:
https://share.getcloudapp.com/GGur1LPW

There are the same console errors in the console as for `#1`

**Comment by camsaul** [comment]
@nemanjaglumac it seems to be working now after I merged the release branch back in.

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac it seems to be working now after I merged the release branch back in.

@camsaul unfortunately, I think this is just a coincidence. There is a rendering issue and it doesn't always work the same. That's why test is intermittently failing. This last time it passed simply because there was no loading spinner when Cypress was asserting.

I am concerned about those rendering issues and console errors. Please see [this](https://github.com/metabase/metabase/pull/13721#issuecomment-724931075) and [this](https://github.com/metabase/metabase/pull/13721#issuecomment-724937289). 😕

**Comment by paulrosenzweig** [comment]
I think the bug fixed in this PR always led to the stuck spinner. Is that right, Cam?

The issue you're seeing where the text doesn't appear is probably a separate thing we need to fix. Maybe we should leave the tests skipped as repros for a new issue around that?

**Comment by camsaul** [comment]
Right, this PR was just to fix an error that caused the whole thing to never load

**Comment by nemanjaglumac** [comment]
> Maybe we should leave the tests skipped as repros for a new issue around that?

My concern is that the test will keep failing even with those positive assertions skipped, as it did [here](https://app.circleci.com/pipelines/github/metabase/metabase/10244/workflows/1a31f772-976b-46cf-80b6-cbfa598cead8/jobs/363412/tests).

If you want, we can skip the whole test and reintroduce it as a repro for this new issue?

**Comment by paulrosenzweig** [comment]
Yeah sorry what I said doesn't make much sense. It's hard to have a repro for an intermittent bug.

Skipping the whole thing sounds good. Maybe we mark it as "quarantined" until we figure out the rendering issue. Is that a corruption of "quarantined" since it's an app flake rather than a test flake?

**Comment by nemanjaglumac** [comment]
> Is that a corruption of "quarantined" since it's an app flake rather than a test flake?

Tbh, not sure. But I'll leave the link to the comments in this thread.

@camsaul are you ok with me skipping the whole test and commiting that with `[ci skip]` flag so that we don't have to go through the CI hell again? You can just merge it after that.

**Comment by camsaul** [comment]
go for it

**Comment by nemanjaglumac** [comment]
So, it turns out there is already an issue for what I was describing as rendering problems in this PR:
https://github.com/metabase/metabase/issues/12506
