### PR TITLE
fixing onFieldUpdate and unskipping tests

### LINKED ISSUE #32345: Metadata column formatting tab stopped working in v0.47.0-RC2
### Describe the bug

Formatting tab not saving changes due to a UI bug that throws `Uncaught TypeError: r is not a function`:

### To Reproduce

1. Go to Admin -> Table Metadata
2. Select a table to edit
3. Select a column to edit
4. Select Formatting tab
5. Change anything like `Display As`
6. See error in dev console

### Expected behavior

_No response_

### Logs

```
react-dom.production.min.js:52 Uncaught TypeError: r is not a function
    at FieldFormattingSettings.tsx:40:7
    at ColumnSettings.jsx:48:9
    at c (settings.js:134:5)
    at Toggle.tsx:25:19
    at Object.c (react-dom.production.min.js:14:84)
    at f (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at m (react-dom.production.min.js:15:72)
    at ct (react-dom.production.min.js:52:170)
    at Array.forEach (<anonymous>)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.7+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.7+7",
    "os.name": "Linux",
    "os.version": "5.15.0-71-generic",
    "user.language": "en",
    "user.timezone": "Asia/Baku"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.30"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-29",
      "tag": "v0.47.0-RC2",
      "branch": "release-x.47.x",
      "hash": "7015512"
    },
    "settings": {
      "report-timezone": "Asia/Baku"
    }
  }
}
```

### Severity

None

### Additional context

I think it was working in 0.46

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/32345

### Description
This PR does 2 things. It assigns the correct action to the `onFieldUpdate` dispatchToActions map, as well as unskipps the `fields.cy.spec.js` tests, as they have been skipped for about 3 years now. 

### How to verify

1. Go to Admin -> Table Metadata
2. Pick a table, then press the gear icon for one of the columns
3. On the left hand sidepanel, select formatting and try to change a setting. You should see a toast confirming the that setting has changed, and refreshing the page should persist your changes.

### Demo
chrome_kzaXBwCSGo

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
Stress test revealed failures in the JSON unfolding. I think UI changed and the test needs to be updated.
https://github.com/metabase/metabase/actions/runs/5654107690/job/15316515376

Great news is that all other tests passed 20/20 ✅

**Review by nemanjaglumac — APPROVED** [review]
Please adapt and fix JSON unfolding test first.
Otherwise, GTG.

**Comment by npfitz** [comment]
Talked with Nemanja, Will be merging this and keeping an eye on potentially flakey test, though it seems to pass in regular CI tests (and locally)
