### ISSUE TITLE
Spark SQL cannot read Hive database after upgrading to 0.39.3

### ISSUE THREAD

**Issue by ikbin** [metabase/metabase#16550]
I was previously on Metabase 0.38.3 version. Previously I was able to read Hive data By Spark SQL.
Spark SQL Query gives an error after I upgraded to 0.39.3

**Logs**

``` 
Exception in thread "C3P0PooledConnectionPoolManager[identityToken->1bqrxirah1w0y5osrj2m7n|13daa4a0]-HelperThread-#2" java.lang.NoClassDefFoundError: java/sql/ShardingKey
 	at java.lang.Class.getDeclaredMethods0(Native Method)
 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
 	at java.lang.Class.getMethod0(Class.java:3018)
 	at java.lang.Class.getMethod(Class.java:1784)
 	at com.mchange.v2.c3p0.impl.C3P0ImplUtils.supportsMethod(C3P0ImplUtils.java:286)
 	at com.mchange.v2.c3p0.impl.NewPooledConnection.<init>(NewPooledConnection.java:117)
 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:181)
 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
 	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
 	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
 	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
 Caused by: java.lang.ClassNotFoundException: java.sql.ShardingKey
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
 	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
 	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
 	... 15 more 
```
- Your browser and the version:  Chrome 91.0
- Your operating system: CentOS Linux 7.7.1908
- Your databases: Hive
- Metabase version: 0.39.3
- Metabase hosting environment: Linux
- Metabase internal database: MySQL

**Comment by flamber** [comment]
Hi @ikbin 
Please post "Diagnostic Info" from Admin > Troubleshooting, and which version of Hive you're using.
It's not a lot of information to go on, so if you can provide some specifics into how to reproduce this problem, then there's a greater chance of it getting fixed.

**Comment by ikbin** [comment]
Hi @flamber  thanks for your reply.

We're currently using Hive 3.1.1.
When I synchronize the database, it reports these errors.
I reused Metabase 0.39.2 to connect to Hive in a new environmen and it worked fine. I was able to view the Hive data.
But when I replace it with Metabase 0.39.3, it still gets this error. It seems to start at 0.39.3.

**Metabase Diagnostic Info**
```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.12.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "sparksql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.29-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.3",
      "date": "2021-05-27",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
@ikbin Can you try with the latest LTS version of Java 11?
https://www.metabase.com/docs/latest/operations-guide/java-versions.html

I have absolutely no idea how this only started on 0.39.3, since there's nothing in the code that hints at what could have caused this: https://github.com/metabase/metabase/compare/v0.39.2...v0.39.3

**Comment by flamber** [comment]
Okay, so the driver looks like it's corrupted during build - there's a 8MB difference between 0.39.2 and 0.39.3, and no changes to the driver https://github.com/metabase/metabase/commits/release-x.39.x/modules/drivers/sparksql:
```
$  ls -l plugins-39.2/
-rw-rw-r-- 1   645601 May 17 20:32 bigquery.metabase-driver.jar
-rw-rw-r-- 1   310456 Feb 26 12:20 csv.metabase-driver.jar
-rw-rw-r-- 1   528265 May 17 20:32 druid.metabase-driver.jar
-rw-rw-r-- 1   735719 May 17 20:32 googleanalytics.metabase-driver.jar
-rw-rw-r-- 1  1061593 May 17 20:32 google.metabase-driver.jar
-rw-rw-r-- 1  4626729 May 17 20:32 mongo.metabase-driver.jar
-rw-rw-r-- 1    91054 May 17 20:32 oracle.metabase-driver.jar
-rw-rw-r-- 1   166207 May 17 20:32 presto.metabase-driver.jar
-rw-rw-r-- 1  1006113 May 17 20:32 redshift.metabase-driver.jar
-rw-rw-r-- 1 30211666 May 17 20:32 snowflake.metabase-driver.jar
-rw-rw-r-- 1 60934886 May 17 20:30 sparksql.metabase-driver.jar
-rw-rw-r-- 1  7134249 May 17 20:32 sqlite.metabase-driver.jar
-rw-rw-r-- 1  1381124 May 17 20:32 sqlserver.metabase-driver.jar
-rw-rw-r-- 1    56071 May 17 20:32 vertica.metabase-driver.jar

$  ls -l plugins-39.3/
-rw-rw-r-- 1   645602 May 27 17:13 bigquery.metabase-driver.jar
-rw-rw-r-- 1   310456 Feb 26 12:20 csv.metabase-driver.jar
-rw-rw-r-- 1   528267 May 27 17:13 druid.metabase-driver.jar
-rw-rw-r-- 1   735720 May 27 17:13 googleanalytics.metabase-driver.jar
-rw-rw-r-- 1  1061593 May 27 17:13 google.metabase-driver.jar
-rw-rw-r-- 1  4626759 May 27 17:13 mongo.metabase-driver.jar
-rw-rw-r-- 1    91055 May 27 17:13 oracle.metabase-driver.jar
-rw-rw-r-- 1   166204 May 27 17:13 presto.metabase-driver.jar
-rw-rw-r-- 1  1006115 May 27 17:13 redshift.metabase-driver.jar
-rw-rw-r-- 1 30211667 May 27 17:13 snowflake.metabase-driver.jar
-rw-rw-r-- 1 52969974 May 27 17:12 sparksql.metabase-driver.jar
-rw-rw-r-- 1  7134245 May 27 17:13 sqlite.metabase-driver.jar
-rw-rw-r-- 1  1381124 May 27 17:13 sqlserver.metabase-driver.jar
-rw-rw-r-- 1    56071 May 27 17:13 vertica.metabase-driver.jar
```

**Comment by ikbin** [comment]
Thanks @flamber  It looks like the error caused by the driver. I replaced the driver and it works.

**Comment by camsaul** [comment]
@ikbin what Java version are you using?

**Comment by camsaul** [comment]
I built the last release with Java 14, I'm guessing one of the Spark SQL deps gets included differently under that (e.g. does stuff like uses the `java.sql.ShardingKey` class) that are only available on newer versions of Java as a result. That would explain the size difference too (e.g. because it can use `java.sql.ShardingKey` it can omit some workaround lib for older Java version support).

There's probably some sort of Java compiler flag or JVM option we can set to force it to build with Java 8 compatibility. Or we can just make sure to build with Java 8 for the foreseeable future because weird things like this can break in ways we didn't expect.

We can fix this for the next release

**Comment by flamber** [comment]
@ikbin This is fixed in 0.39.4, so please try that release.
