### ISSUE TITLE
Metadata column formatting tab stopped working in v0.47.0-RC2

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [metabase/metabase#32345]
### Describe the bug

Formatting tab not saving changes due to a UI bug that throws `Uncaught TypeError: r is not a function`:

### To Reproduce

1. Go to Admin -> Table Metadata
2. Select a table to edit
3. Select a column to edit
4. Select Formatting tab
5. Change anything like `Display As`
6. See error in dev console

### Logs

```
react-dom.production.min.js:52 Uncaught TypeError: r is not a function
    at FieldFormattingSettings.tsx:40:7
    at ColumnSettings.jsx:48:9
    at c (settings.js:134:5)
    at Toggle.tsx:25:19
    at Object.c (react-dom.production.min.js:14:84)
    at f (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at m (react-dom.production.min.js:15:72)
    at ct (react-dom.production.min.js:52:170)
    at Array.forEach (<anonymous>)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.7+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.7+7",
    "os.name": "Linux",
    "os.version": "5.15.0-71-generic",
    "user.language": "en",
    "user.timezone": "Asia/Baku"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.30"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-29",
      "tag": "v0.47.0-RC2",
      "branch": "release-x.47.x",
      "hash": "7015512"
    },
    "settings": {
      "report-timezone": "Asia/Baku"
    }
  }
}
```

### Severity

None

### Additional context

I think it was working in 0.46
