### ISSUE TITLE
Impersonation in Snowflake fails if role name contains `-` (dash)

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#73788]
### Describe the bug

All queries with impersonation in 1.60.4 fail if role name contains `-`

### To Reproduce

Not yet reproduced, but steps from customer are:

1. Connect to Snowflake database source
2. Enable impersonation
3. Use rolenames with `-`
4. Queries all fail with `...Error processing query: SQL compilation error:syntax error line 1 at position 5 unexpected '-' ...`

### Expected behavior

Expect queries to work with `-` since they did in 1.60.3.8

### Information about your Metabase installation

```JSON
v1.60.4
```

### Severity

P1

**Comment by likeshumidity** [comment]
rollback to 1.60.3.8 fixed issue.
