### ISSUE TITLE
Frontend crashes when using a custom column on a nested query

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18814]
**Describe the bug**
When building a nested query with a custom column, the frontend crashes when doing a "group by" by this column on the second stage of the question 

**Logs**
No logs on the backend, the frontend crashes with
<details>
Dimension.js:450 Unknown MBQL Field clause (2) ['expression', 'a-year-in_middlescores']

react-dom.production.min.js:209 TypeError: a.mbql is not a function

react-dom.production.min.js:50 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
</details>

**To Reproduce**
1) With the orders table do a "Count" by "Created at: year"
2) Build a custom column with the [Created At] field
3) Now summarize again by "Count" and select the newly created custom column

**Expected behavior**
It should show the result, in fact the preview works correctly, but when you click in visualize it won't work

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/139914295-380823eb-a16a-4860-8977-ac3de7fe7fbb.png)
![image](https://user-images.githubusercontent.com/1711649/139914317-8d8e4171-87d1-4421-92f6-aef140e437f1.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: sample dataset
- Metabase version: 41.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Regression since 0.40.0 - works on 0.39.5

**Comment by spectorar** [comment]
Is there a way to workaround this without downgrading to 0.39.5 (which makes me uncomfortable going from 0.41). We have a couple visualizations that are experiencing this issue. Is there a planned version for a fix? Thanks!

**Comment by paoliniluis** [comment]
> Is there a way to workaround this without downgrading to 0.39.5 (which makes me uncomfortable going [from 0.41](x-apple-data-detectors://9)). We have a couple visualizations that are experiencing this issue. Is there a planned version for a fix? Thanks!

Not currently. I would suggest you do a native sql question instead of downgrading which could cause very unexpected consequences

**Comment by flamber** [comment]
@spectorar Yes, since the problem comes from the Notebooks handling of the field references, which doesn't exist in SQL.

**Comment by ariya** [comment]
The error thrown by the front-end, because our `TimeseriesFilterWidget` does not take into account that the filtered dimension can be of an expression (i.e. due to the custom column), and not just a vanilla field from the table.

![image](https://user-images.githubusercontent.com/7288/153964798-dda09e39-e435-4140-9eb4-8d4584da18f3.png)

Next step: teach `TimeseriesFilterWidget` to generalize the filter dimension, for both field and expression.
