### PR TITLE
[MBQL lib] Ignore `inherited-temporal-unit` on bucketed columns

### LINKED ISSUE #70231: Hashed alias in model becomes unresolvable after upgrade when model uses date-transformed joined field with sandboxing
## Describe the bug

After upgrading from v1.55.16.4 to v1.58.7, a GUI question that references a model with date-transformed joined columns fails with two different errors depending on the user:

**Admin sees:**
> Join condition refers to a column from outside this join, but it was incorrectly resolved to a column from this join.

**Sandboxed user sees:**
> SQL compilation error: error line 1 at position 2,356 invalid identifier '"source"."Replenishment Order Form Submitted Answer Label = Y_1fa45e07"'

The question and model worked correctly on v1.55.16.4 before the upgrade.

The model has a join between two Snowflake tables, and the joined table contains columns with long names (>60 bytes), causing Metabase to generate CRC-32 hashed aliases (e.g., `Y_1fa45e07`). These hashed aliases become unresolvable in the outer query scope after upgrade.

## To Reproduce (user reported steps)

1. On v1.55.16.4: Create a GUI model joining two Snowflake tables (e.g., ORDERS joined to PRODUCTS on a shared key)
2. Both tables contain columns with long names (>60 characters), such as `Replenishment Order Form Submitted Answer Label` or `Product Availability Inventory Restock Schedule Date`
3. Include date-transformed fields from the joined table in the model output
4. Create a GUI question based on this model that uses aggregation (e.g., `distinct-where` or `count` with a `GROUP BY` on a date column from the joined table)
5. Configure row-level sandbox (data sandbox) policies on both underlying tables, filtering by a user attribute (e.g., `user_id`)
6. Verify the question works on v1.55.16.4 for both admin and sandboxed users
7. Upgrade to v1.58.7 (standard upgrade, Metabase runs migrations on the app DB)
8. Run the same question on v1.58.7

**Expected:** Question executes successfully, as it did on v1.55.16.4.

**Actual (admin):** "Join condition refers to a column from outside this join, but it was incorrectly resolved to a column from this join."

**Actual (sandboxed user):** SQL compilation error — the hashed alias (e.g., `Y_1fa45e07`) appears in the generated SQL but Snowflake cannot resolve it.

**Note:** We attempted reproduction via upgrade path simulation (v1.55 → v1.58 with Snowflake) — did not reproduce. The user's scenario likely requires more complex aggregation patterns (`distinct-where`), more columns/joins, and multiple simultaneous sandbox policies to trigger. The reproduction environment used PostgreSQL as app DB while the user uses MySQL 8.0.28.

## Expected behavior

Hashed aliases generated for long column names in joined tables should remain resolvable in outer query scopes after sandbox wrapping, matching v1.55.16.4 behavior.

## Logs

**Admin backend error (from diagnostic download):**
```
Error processing query: SQL compilation error: error line 1 at position 2,356
invalid identifier '"source"."Replenishment Order Form Submitted Answer Label = Y_1fa45e07"'

Stacktrace (top frames):
  driver.sql_jdbc.execute$execute_reducible_query (execute.clj:780)
  driver.sql_jdbc.execute$do_with_resolved_connection (execute.clj:348)
  driver.sql_jdbc.execute$execute_reducible_query (execute.clj:770)
  query_processor.pipeline$*execute* (pipeline.clj:59)
  query_processor.execute$run (execute.clj:72)
```

**Sandboxed user:** Returns HTTP 403 (sandbox wrapping itself fails before query execution).

## Information about your Metabase Installation

- Metabase v1.58.7 (Enterprise, self-hosted)
- Previous version: v1.55.16.4 (worked correctly)
- Application database: MySQL 8.0.28
- Data warehouse: Snowflake

## Severity

Blocking — user upgraded for security advisory GHSA-vcj8-rcm8-gfj9 and cannot downgrade. No GUI workaround available.

### Related issues

| Issue | Title | Relevance |
|-------|-------|-----------|
| #66405 | RCLS with SQL questions + long column names | Same hashed alias mechanism — was fixed in v56.x |
| #64050 | Hiding PK causes `desired-alias->escaped` error | Same alias resolution failure pattern — fixed in v58 |
| #66781 | CLS hides columns from joined table | Sandbox column mismatch — fixed in v57.5+ |
| #66617 | Deselecting fields busts questions for RCLS users | Same class of column mismatch — OPEN |

### MySQL application database note

The user's application database is MySQL 8.0.28 (reproduction used PostgreSQL). The v57 MBQL 4→5 migration had a known bug where some cards could end up with `dataset_query = '{}'`. Additionally, MySQL's `NO_BACKSLASH_ESCAPES` SQL mode can cause `column_settings` key migrations to silently skip. These are potential contributing factors worth checking during investigation.

### Upgrade history note

The user reports encountering compatibility issues with every major version upgrade. This means the instance has been through multiple upgrade cycles, and each may have involved partial failures, rollbacks, or hotfixes applied mid-migration. The bug's root cause could have been introduced at any point during a previous upgrade failure — or by a fix applied to recover from one — leaving the app DB or card metadata in an intermediate state that only becomes visible after a later upgrade. Investigation should consider the cumulative effect of multiple upgrade cycles, not just the v1.55 → v1.58 transition in isolation.

### Workaround

No GUI workaround available. The user cannot modify the hashed alias behavior through the question builder.

### PR DESCRIPTION
**Pull request by bshepherdson**
closes #70231
Fixes QUE2-394.

### Description

This issue was caused by losing the thread of a column between stages in
the case where it has a different `:inherited-temporal-unit` than its
proper `:temporal-unit`.

`lib.equality/=` was checking the `:temporal-unit`s, which match, and
then returning `false` because only one column had
`:inherited-temporal-unit` for a different, finer unit. That shouldn't
fail the match, since the `:inherited-temporal-unit` is obsolete when
the column has just been bucketed differently.

### How to verify

This is hard to reproduce based on the bug; the input query is a monster with numerous nested and joined models.
I tested this locally by preprocessing and compiling the user query based on an appdb dump, and the fix in this PR
fixes the syntax of their query. (Of course I couldn't run it for real, but the syntax checks out.)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- ~~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~~

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#70512** <a href="https://app.graphite.com/github/pr/metabase/metabase/70512?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/metabase/metabase/70512?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ranquild — APPROVED** [review]

**Review by metamben — APPROVED** [review]

**Comment by likeshumidity** [comment]
@bshepherdson any idea why this isn't merging? Trying to get released to customer tmo if possible.

**Comment by bshepherdson** [comment]
> @bshepherdson any idea why this isn't merging? Trying to get released to customer tmo if possible.

Looks like the usual flaky CI nonsense. I've given the tests another kick. Note that we'll need to get 58 and 59 backports to land too, and they'll have the same problems.
