### ISSUE TITLE
Pulse email fails due to Batik Error

### ISSUE THREAD

**Issue by JesseDyer** [metabase/metabase#19620]
**Describe the bug**
Since upgrading to 0.41.5, I find that my pulses no longer email.  Note, the same error occurs when testing the Send Now function of Dashboard Subscription via email.

My email credential and test send in the UI function as expected.  When I open the UI, I get:
Jan 11 09:26:54 metabase metabase[1481]: 2022-01-11 09:26:54,986 ERROR middleware.log :: #033[31mPOST /api/pulse/test 500 359.8 ms (14 DB calls)
Jan 11 09:26:54 metabase metabase[1481]: {:via
Jan 11 09:26:54 metabase metabase[1481]:  [{:type java.lang.NoClassDefFoundError,
Jan 11 09:26:54 metabase metabase[1481]:    :message "Could not initialize class org.apache.batik.bridge.CursorManager",
Jan 11 09:26:54 metabase metabase[1481]:    :at [org.apache.batik.bridge.BridgeContext <init> "BridgeContext.java" 1162]}],
Jan 11 09:26:54 metabase metabase[1481]:  :trace
Jan 11 09:26:54 metabase metabase[1481]:  [[org.apache.batik.bridge.BridgeContext <init> "BridgeContext.java" 1162]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.bridge.BridgeContext <init> "BridgeContext.java" 292]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.transcoder.SVGAbstractTranscoder createBridgeContext "SVGAbstractTranscoder.java" 338]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.transcoder.SVGAbstractTranscoder createBridgeContext "SVGAbstractTranscoder.java" 314]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.transcoder.SVGAbstractTranscoder transcode "SVGAbstractTranscoder.java" 196]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.transcoder.image.ImageTranscoder transcode "ImageTranscoder.java" 92]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.transcoder.XMLAbstractTranscoder transcode "XMLAbstractTranscoder.java" 142]
Jan 11 09:26:54 metabase metabase[1481]:   [org.apache.batik.transcoder.SVGAbstractTranscoder transcode "SVGAbstractTranscoder.java" 158]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse.render.js_svg$render_svg invokeStatic "js_svg.clj" 97]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse.render.js_svg$render_svg invoke "js_svg.clj" 87]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse.render.js_svg$svg_string__GT_bytes invokeStatic "js_svg.clj" 101]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse.render.js_svg$svg_string__GT_bytes invoke "js_svg.clj" 100]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse.render.js_svg$icon invokeStatic "js_svg.clj" 160]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse.render.js_svg$icon invoke "js_svg.clj" 154]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.email.messages$icon_bundle invokeStatic "messages.clj" 79]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.email.messages$icon_bundle invoke "messages.clj" 76]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.email.messages$render_message_body invokeStatic "messages.clj" 462]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.email.messages$render_message_body invoke "messages.clj" 455]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.email.messages$render_pulse_email invokeStatic "messages.clj" 484]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.email.messages$render_pulse_email invoke "messages.clj" 481]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$fn__58996 invokeStatic "pulse.clj" 313]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$fn__58996 invoke "pulse.clj" 302]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.MultiFn invoke "MultiFn.java" 239]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$results__GT_notifications$iter__59026__59030$fn__59031 invoke "pulse.clj" 365]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.LazySeq sval "LazySeq.java" 42]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.LazySeq seq "LazySeq.java" 51]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.RT seq "RT.java" 535]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.core$seq__5419 invokeStatic "core.clj" 139]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.core$seq__5419 invoke "core.clj" 139]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$send_notifications_BANG_ invokeStatic "pulse.clj" 407]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$send_notifications_BANG_ invoke "pulse.clj" 406]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$send_pulse_BANG_ invokeStatic "pulse.clj" 435]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.pulse$send_pulse_BANG_ doInvoke "pulse.clj" 415]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.RestFn invoke "RestFn.java" 410]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.api.pulse$fn__79282 invokeStatic "pulse.clj" 211]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.api.pulse$fn__79282 invoke "pulse.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_response$fn__32066 invoke "core.clj" 160]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_middleware$fn__32050 invoke "core.clj" 132]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_info$fn__32055 invoke "core.clj" 139]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 151]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 153]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 153]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 153]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 152]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078 invoke "core.clj" 200]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.auth$enforce_authentication$fn__70354 invoke "auth.clj" 14]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078 invoke "core.clj" 200]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$handler__32106 invoke "core.clj" 289]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 299]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.api.routes$fn__79831$fn__79834 invoke "routes.clj" 56]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078 invoke "core.clj" 200]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.AFn applyToHelper "AFn.java" 160]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.AFn applyTo "AFn.java" 144]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.core$apply invokeStatic "core.clj" 667]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.core$apply invoke "core.clj" 662]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.routes$fn__79976$fn__79977 doInvoke "routes.clj" 57]
Jan 11 09:26:54 metabase metabase[1481]:   [clojure.lang.RestFn invoke "RestFn.java" 436]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078 invoke "core.clj" 200]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$handler__32106 invoke "core.clj" 289]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$make_context$fn__32110 invoke "core.clj" 299]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 153]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 153]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 153]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.routes$fn__79964$fn__79966 invoke "routes.clj" 41]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
Jan 11 09:26:54 metabase metabase[1481]:   [compojure.core$routes$fn__32078 invoke "core.clj" 200]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77436 invoke "exceptions.clj" 98]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77433 invoke "exceptions.clj" 86]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.log$log_api_call$fn__80431$fn__80432$fn__80433 invoke "log.clj" 209]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.log$log_api_call$fn__80431$fn__80432 invoke "log.clj" 201]
Jan 11 09:26:54 metabase metabase[1481]:   [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
Jan 11 09:26:54 metabase metabase[1481]:   [toucan.db$_do_with_call_counting invoke "db.clj" 209]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.log$log_api_call$fn__80431 invoke "log.clj" 200]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83644 invoke "browser_cookie.clj" 30]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.security$add_security_headers$fn__59281 invoke "security.clj" 147]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.json$wrap_json_body$fn__82788 invoke "json.clj" 62]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.json$wrap_streamed_json_response$fn__82806 invoke "json.clj" 98]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.offset_paging$handle_paging$fn__59305 invoke "offset_paging.clj" 42]
Jan 11 09:26:54 metabase metabase[1481]:   [ring.middleware.keyword_params$wrap_keyword_params$fn__83911 invoke "keyword_params.clj" 55]
Jan 11 09:26:54 metabase metabase[1481]:   [ring.middleware.params$wrap_params$fn__83927 invoke "params.clj" 69]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.misc$maybe_set_site_url$fn__34077 invoke "misc.clj" 59]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979 invoke "session.clj" 257]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 238]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 230]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.session$bind_current_user$fn__44978 invoke "session.clj" 256]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.session$wrap_current_user_info$fn__44965 invoke "session.clj" 216]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.session$wrap_session_id$fn__44951 invoke "session.clj" 162]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.auth$wrap_api_key$fn__70362 invoke "auth.clj" 27]
Jan 11 09:26:54 metabase metabase[1481]:   [ring.middleware.cookies$wrap_cookies$fn__83831 invoke "cookies.clj" 216]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.misc$add_content_type$fn__34060 invoke "misc.clj" 27]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.misc$disable_streaming_buffering$fn__34085 invoke "misc.clj" 76]
Jan 11 09:26:54 metabase metabase[1481]:   [ring.middleware.gzip$wrap_gzip$fn__83873 invoke "gzip.clj" 86]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.misc$bind_request$fn__34088 invoke "misc.clj" 93]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83660 invoke "ssl.clj" 48]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server$async_proxy_handler$fn__80204 invoke "server.clj" 71]
Jan 11 09:26:54 metabase metabase[1481]:   [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.server.Server handle "Server.java" 516]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
Jan 11 09:26:54 metabase metabase[1481]:   [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
Jan 11 09:26:54 metabase metabase[1481]:   [java.lang.Thread run "Thread.java" 748]],
Jan 11 09:26:54 metabase metabase[1481]:  :cause "Could not initialize class org.apache.batik.bridge.CursorManager",
Jan 11 09:26:54 metabase metabase[1481]:  :message "Could not initialize class org.apache.batik.bridge.CursorManager"}

**Logs**
See above

**To Reproduce**
1. Navigate to a predefined pulse
2. Click on Send email now
3. No emai lever arrives

**Expected behavior**
An email should be generated.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Edge 97.0.1072.55
- Your operating system: Served from Ubuntu 20.04
- Your databases: Mysql 10.3.32
- Metabase version: 0.41.5
- Metabase hosting environment: VMWare Installation
- Metabase internal database: Mysql 10.3.32

**Severity**
I use the pulse function to communicate issues to third parties, so for me, this is somewhat urgent.

**Comment by paoliniluis** [comment]
Which Java version do you have? Please post this on the forums. Thanks!

**Comment by JesseDyer** [comment]
Ha!  Sorry for this; I'm on an old (8) version of Java.  Updated, and my pulse is working perfectly.
