### PR TITLE
Settings email form fixes

### LINKED ISSUE #12274: Clearing email settings requires a manual browser reload to show "changes"
**Describe the bug**
Clicking "Clear" button on Admin > Settings > Email does nothing (or so it seems). Requires are browser reload to show empty fields again.
Used to work on 0.34.3

**To Reproduce**
1. Go to Admin > Settings > Email
2. (if not already enabled, then fill out the info and Save, and do a browser reload)
3. Click "Clear" button, which sends a `DELETE /api/email 204`, but the fields are not emptied until doing a manual browser reload

**Information about your Metabase Installation:**
Metabase 0.35.1, various backends and browsers.

**Additional context**
I guess it might have something to do with the request now being `204` instead of `200`?
Related to #7504

### LINKED ISSUE #12275: Cannot send test email
**Describe the bug**
Cannot send test email. The button changes to "Sending...", but nothing happens.

**To Reproduce**
1. Go to Admin > Settings > Email
2. (fill out email settings - doesn't matter if it is correct or not - Save)
3. Click "Send test email" - the button changes to "Sending...", but nothing happens beyond that.
4. The browser console says `TypeError: r._form.setFormErrors is not a function`, but there's no request to `/api/email/test`, so no success/error message either.

**Information about your Metabase Installation:**
Metabase 0.35.1, various backends and browsers.

**Additional context**
This used to work on 0.34.3 - it would send the request and display a message, in case of error, something like `Sorry, something went wrong. Please try again.` (real error is in the logs, but that's covered by #1692)

### PR DESCRIPTION
**Pull request by tlrobinson**
When we `connect`ed `SettingsBatchForm` it broke `SettingsEmailForm`.

Resolves #12274 
Resolves #12275 

A Cypress test would be nice but we'd need to spin up a test SMTP server.

### CODE REVIEW

**Review by flamber — APPROVED** [review]
This fixes both issues.

Couldn't we just test this without the SMTP? We should see an error, when using `fake.smtp.server.example` as SMTP Host.

**Review by paulrosenzweig — APPROVED** [review]

**Review by kdoh — COMMENTED** [review]
I'm with @flamber that some sort of testing would be really helpful here. Could we do something lower level than cypress that doesn't require SMTP to be setup just to have something that fails if this were to break again?

**Comment by tlrobinson** [comment]
The two issues would require valid settings to already be set in order to test sending a test email or clearing the settings, however I can use `cy.route` to mock the requests, so I'll do that.

**Comment by tlrobinson** [comment]
Actually I didn't need to mock since you're allowed to save email settings even if the server isn't reachable.

**Review by kdoh — APPROVED** [review]
