### PR TITLE
Support empty column names in table viz

### LINKED ISSUE #57685: Empty column Names break the SQL Editor
### Describe the bug

This is bad practice but if you alias a column to an empty string the Editor breaks

### To Reproduce

1. Go to New -> SQL Question -> `Select id AS "" from orders` -> Run:

Image

### Expected behavior

The UI doesn't break like that or at least you get a warning that empty column names aren't supported. In previous versions it used to work:

Image

### Logs

Image

```
console.js:13 Error
    at index.mjs:218:15
    at index.mjs:246:1
    at Array.map (<anonymous>)
    at t (index.mjs:2884:27)
    at index.mjs:2891:14
    at Object.getAllColumns (index.mjs:124:14)
    at index.mjs:2904:42
    at Object.getAllLeafColumns (index.mjs:116:21)
    at index.mjs:1514:97
    at index.mjs:1509:26
d.error	@	console.js:13
XMLHttpRequest.send		
(anonymous)	@	api.js:257
_makeRequestWithXhr	@	api.js:215
_makeRequest	@	api.js:210
_makeRequestWithRetries	@	api.js:182
(anonymous)	@	api.js:158
(anonymous)	@	services.js:117
g	@	services.js:130
(anonymous)	@	querying.ts:155
(anonymous)	@	querying.ts:296
(anonymous)	@	NativeQueryEditor.tsx:443

```

### Information about your Metabase installation

```JSON
54 cannot replicate on version 53
```

### Severity

Cosmetic since I doubt many users would be doing this but good to flag

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/57685

Tanstack Table throws an error when the id for a column is the empty string. This PR fixes that by adding a fallback id.

This allows the table to render when some column names are empty strings. This PR also fixes the styling of the header pill for empty column headers.

Note that this PR does not fix any of the myriad of other issues that stem from using empty strings as column names.

Screenshot 2025-05-29 at 11 35 12

### CODE REVIEW

File: e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js [hunk 1]
```diff
@@ -1466,3 +1466,23 @@ WHERE NOT (
       .should("be.visible");
   });
 });
+
```
Comment (kamilmielnik) [inline e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js:1469]: > Note that this PR does not fix any of the myriad of other issues that stem from using empty strings as column names.

1. Go to New -> SQL Question -> `Select id AS "" from orders` -> Run
2. Save as new question
3. Click "Explore results"

QP will fail with `"Invalid output: [{:lib/source-column-alias [\"should be at least 1 character, got: \\\"\\\"\" \"non-blank string, got: \\\"\\\"\"]}]"`

With that in mind, maybe it'd be more appropriate to make QP consistently fail and always require non-empty column names instead?

Comment (romeovs) [reply e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js:1469]: @mngr What do you think. The options are:
- disallow empty column names completely (as per Kamil's suggestion)
- allow them to work in native queries, so users can more freely explore data, but have them break elsewhere.

Comment (mngr) [reply e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js:1469]: @romeovs yes, let's disallow empty column names and show some clear error message like "Empty column names are not supported"

Comment (romeovs) [reply e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js:1469]: Ok, I will close this PR and mark the issue as BE.

**Comment by romeovs** [comment]
Closing due to https://github.com/metabase/metabase/pull/58621#discussion_r2120554351, we wil validate this on the BE.
