### ISSUE TITLE
Hashed alias in model becomes unresolvable after upgrade when model uses date-transformed joined field with sandboxing

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#70231]
## Describe the bug

After upgrading from v1.55.16.4 to v1.58.7, a GUI question that references a model with date-transformed joined columns fails with two different errors depending on the user:

**Admin sees:**
> Join condition refers to a column from outside this join, but it was incorrectly resolved to a column from this join.

**Sandboxed user sees:**
> SQL compilation error: error line 1 at position 2,356 invalid identifier '"source"."Replenishment Order Form Submitted Answer Label = Y_1fa45e07"'

The question and model worked correctly on v1.55.16.4 before the upgrade.

The model has a join between two Snowflake tables, and the joined table contains columns with long names (>60 bytes), causing Metabase to generate CRC-32 hashed aliases (e.g., `Y_1fa45e07`). These hashed aliases become unresolvable in the outer query scope after upgrade.

## To Reproduce (user reported steps)

1. On v1.55.16.4: Create a GUI model joining two Snowflake tables (e.g., ORDERS joined to PRODUCTS on a shared key)
2. Both tables contain columns with long names (>60 characters), such as `Replenishment Order Form Submitted Answer Label` or `Product Availability Inventory Restock Schedule Date`
3. Include date-transformed fields from the joined table in the model output
4. Create a GUI question based on this model that uses aggregation (e.g., `distinct-where` or `count` with a `GROUP BY` on a date column from the joined table)
5. Configure row-level sandbox (data sandbox) policies on both underlying tables, filtering by a user attribute (e.g., `user_id`)
6. Verify the question works on v1.55.16.4 for both admin and sandboxed users
7. Upgrade to v1.58.7 (standard upgrade, Metabase runs migrations on the app DB)
8. Run the same question on v1.58.7

**Expected:** Question executes successfully, as it did on v1.55.16.4.

**Actual (admin):** "Join condition refers to a column from outside this join, but it was incorrectly resolved to a column from this join."

**Actual (sandboxed user):** SQL compilation error — the hashed alias (e.g., `Y_1fa45e07`) appears in the generated SQL but Snowflake cannot resolve it.

**Note:** We attempted reproduction via upgrade path simulation (v1.55 → v1.58 with Snowflake) — did not reproduce. The user's scenario likely requires more complex aggregation patterns (`distinct-where`), more columns/joins, and multiple simultaneous sandbox policies to trigger. The reproduction environment used PostgreSQL as app DB while the user uses MySQL 8.0.28.

## Expected behavior

Hashed aliases generated for long column names in joined tables should remain resolvable in outer query scopes after sandbox wrapping, matching v1.55.16.4 behavior.

## Logs

**Admin backend error (from diagnostic download):**
```
Error processing query: SQL compilation error: error line 1 at position 2,356
invalid identifier '"source"."Replenishment Order Form Submitted Answer Label = Y_1fa45e07"'

Stacktrace (top frames):
  driver.sql_jdbc.execute$execute_reducible_query (execute.clj:780)
  driver.sql_jdbc.execute$do_with_resolved_connection (execute.clj:348)
  driver.sql_jdbc.execute$execute_reducible_query (execute.clj:770)
  query_processor.pipeline$*execute* (pipeline.clj:59)
  query_processor.execute$run (execute.clj:72)
```

**Sandboxed user:** Returns HTTP 403 (sandbox wrapping itself fails before query execution).

## Information about your Metabase Installation

- Metabase v1.58.7 (Enterprise, self-hosted)
- Previous version: v1.55.16.4 (worked correctly)
- Application database: MySQL 8.0.28
- Data warehouse: Snowflake

## Severity

Blocking — user upgraded for security advisory GHSA-vcj8-rcm8-gfj9 and cannot downgrade. No GUI workaround available.

### Related issues

| Issue | Title | Relevance |
|-------|-------|-----------|
| #66405 | RCLS with SQL questions + long column names | Same hashed alias mechanism — was fixed in v56.x |
| #64050 | Hiding PK causes `desired-alias->escaped` error | Same alias resolution failure pattern — fixed in v58 |
| #66781 | CLS hides columns from joined table | Sandbox column mismatch — fixed in v57.5+ |
| #66617 | Deselecting fields busts questions for RCLS users | Same class of column mismatch — OPEN |

### MySQL application database note

The user's application database is MySQL 8.0.28 (reproduction used PostgreSQL). The v57 MBQL 4→5 migration had a known bug where some cards could end up with `dataset_query = '{}'`. Additionally, MySQL's `NO_BACKSLASH_ESCAPES` SQL mode can cause `column_settings` key migrations to silently skip. These are potential contributing factors worth checking during investigation.

### Upgrade history note

The user reports encountering compatibility issues with every major version upgrade. This means the instance has been through multiple upgrade cycles, and each may have involved partial failures, rollbacks, or hotfixes applied mid-migration. The bug's root cause could have been introduced at any point during a previous upgrade failure — or by a fix applied to recover from one — leaving the app DB or card metadata in an intermediate state that only becomes visible after a later upgrade. Investigation should consider the cumulative effect of multiple upgrade cycles, not just the v1.55 → v1.58 transition in isolation.

### Workaround

No GUI workaround available. The user cannot modify the hashed alias behavior through the question builder.

**Comment by bshepherdson** [comment]
My hypothesis is that the issue comes from the _truncation_ of long names (that part is obvious). The tricky part is that way back (earlier than 55) Metabase had cases where the truncated names would get used in refs. Those truncated names aren't stable, especially when the query is modified by things like sandboxing. That leaves the refs by truncated name as dangling refs, and the query fails.

I'm trying to reproduce this by creating tables, fields, models and questions in 48, then upgrading to 55, then to 58.

**There might be a user-level workaround,** but I have to warn you that without knowing the details of this model it's impossible for me to predict the fallout. Trying this might break all/many consumers of this model. If there's only a handful, maybe that's fine; if there are hundreds, then don't do this!

If you want to try it, the fix looks like this:
- Edit the model's query. It needs to be a real edit that gets saved. Say, adding an extra `count` aggregation, or an expression that adds 1 to some number.
    - _This perturbs the model so that the next edit is real and doesn't get dropped because there's "no change."_
- Edit the model's query again:
    - Delete all the parts of the query right back to the main source.
    - Rebuild it, without the extra `count` or expression.
    - _This replaces the bad refs with truncated names that I mentioned._
- For each downstream query:
    - For each use of a column from the model:
        - Drop it, and recreate it.
        - That includes uses in join conditions, as the FK of an implicit join, or in the field selection drop down.

As I say, that isn't practical if there's loads of downstream queries, but if there's only a few it would then this will be the quickest way to work around this issue.

We fixed _generating_ these bad refs based on truncated column names several versions ago, but it doesn't repair pre-exisiting ones created by older versions of Metabase. If we can successfully reproduce this issue or something like it, then perhaps it is practical to repair these refs.
