### PR TITLE
Fix notebook editor crash when joining on a custom column

### LINKED ISSUE #18818: Cannot access Notebook for questions that uses a Custom Column as joining column
**Describe the bug**
Cannot access Notebook for questions that uses a Custom Column as joining column.
Trying to access the Notebook editor will cause a frontend reload, which is constantly sending `/api/card/:id` until browsing away.
Got a blank screen at some point too (think I tested on master).

Regression since 0.41.0

**To Reproduce**
1. On 0.40.5: Custom question > Sample Dataset > Reviews
2. Custom Column `[Rating]` as "CC just Rating"
3. Join Orders on "CC just Rating"="Quantity"
4. Summarize Count grouped by CreatedAt:Year
image
5. Save question, upgrade to 0.41.1, open the question (load results fine), but trying to access Notebook will cause the frontend to reload constantly.
The browser console is drowning in various errors like:
```
Error thrown while validating clause i {fields: 'all', source-table: 11, condition: Array(3), alias: 'Orders', strategy: 'inner-join', …} TypeError: Cannot read properties of undefined (reading 'CC just Rating')
    at n.value (Dimension.js:1025)
    at StructuredQuery.js:1107
    at Array.map (<anonymous>)
    at StructuredQuery.js:1104
    at Array.map (<anonymous>)
    at n.value (StructuredQuery.js:1102)
    at n.value (StructuredQuery.js:1154)
    at i.value (Join.js:587)
    at n.value (StructuredQuery.js:462)
    at n.value (StructuredQuery.js:453)

TypeError: e.temporalUnit is not a function
    at JoinStep.jsx:550
    at qEe (JoinStep.jsx:566)
    at Qo (react-dom.production.min.js:153)
    at xs (react-dom.production.min.js:261)
    at vu (react-dom.production.min.js:246)
    at gu (react-dom.production.min.js:246)
    at uu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vi (react-dom.production.min.js:122)
```

**Information about your Metabase Installation:**
Tested 0.39.5 thru 0.41.1 and commit `8f65be8` (latest 41.2 branch).

**Additional context**
Related to #18630

### PR DESCRIPTION
**Pull request by kulyk**
Reproduces #18818, fixes #18818

The notebook editor crashes if you open a question with a join on a custom column. For the same reason, trying to join on a custom column fails too. Caused by #17883 (ability to select temporal units for join fields)

### To Verify

1. Ask a question > Sample Dataset > Reviews
2. Add a custom column: `[Rating]` as "CC just Rating"
3. Join the Orders table on `CC just Rating = Quantity`
4. Nothing should crash

### Demo

**Before (and a proof the repro works**

Everything is just blank because it crashed 🤷 

CleanShot 2021-11-04 at 19 28 03@2x

**After**

https://user-images.githubusercontent.com/17258145/140390963-dc925d21-39ea-488f-ae6f-4e797188d68c.mov

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx [hunk 1]
```diff
@@ -547,7 +547,7 @@ function getDimensionDisplayName(dimension) {
   if (!dimension) {
     return t`Pick a column...`;
   }
-  if (dimension.temporalUnit()) {
+  if (isDateTimeField(dimension.mbql())) {
```
Comment (kulyk) [inline frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx:550]: `temporalUnit` method does not exist on `ExpressionDimension` instances, so that's why it fails. Fixed by checking MBQL instead

**Review by ariya — APPROVED** [review]
LGTM. Ship it :rocket:

**Review by flamber — APPROVED** [review]

**Comment by rlotun** [comment]
🙏🏽 Thank you @kulyk
