### PR TITLE
Mantine TextInput and NumberInput

### PR DESCRIPTION
**Pull request by ranquild**
How to verify:
- `yarn storybook`
- Open http://localhost:6006/?path=/docs/inputs-textinput--default-story
- Compare with https://www.figma.com/file/oIZhYS5OoRA7twd4KqN4Eu/Input-%2F-Text?type=design&node-id=5-70&mode=design&t=dsUIfXbrSyAZT8ku-0

Note that there is no "truncated" variant since native inputs don't change their content this way.

Screenshot 2023-08-23 at 17 17 51

### CODE REVIEW

File: frontend/src/metabase/ui/components/inputs/Input/Input.styled.tsx [hunk 1]
```diff
@@ -0,0 +1,121 @@
+import { getSize, rem } from "@mantine/core";
+import type { InputStylesParams, MantineThemeOverride } from "@mantine/core";
+
+const SIZES = {
+  xs: rem(28),
+  md: rem(40),
+};
+
+const PADDING = 12;
```
Comment (ranquild) [inline frontend/src/metabase/ui/components/inputs/Input/Input.styled.tsx:9]: We need to do some basic math with these vars, that's why I don't convert them to `rem` here to avoid using `calc` where not needed

**Comment by uladzimirdev** [comment]
@ranquild for some reason I have locally

```
frontend/src/metabase/ui/Intro.stories.mdx: isTSSatisfiesExpression is not a function`
```

**Comment by ranquild** [comment]
@uladzimirdev can't repro locally

**Comment by uladzimirdev** [comment]
### 1. top-bottom padding inside input

seems line-height is not specified correctly, I see for MD 40px vs 24px in figma

#### PR
image

#### figma
image

#### mantine
image

### 2. margin-top for input

having this dom structure I don't think adding margin to input is a good idea. I would consider using `gap` on root or margin-bottom on prev component (label) or margin-top on an input wrapper as the last resort.

image

### 3. borderless input
is not aligned on the left with a label
image

--------------------------

And overall visually borderless input looks not great, I would cut internal padding in it
image
image

File: frontend/src/metabase/ui/theme.ts [hunk 2]
```diff
@@ -95,8 +98,10 @@ export const getThemeOverrides = (): MantineThemeOverride => ({
     ...getAnchorOverrides(),
     ...getButtonOverrides(),
     ...getCheckboxOverrides(),
+    ...getInputOverrides(),
```
[the remark this answers is not in the document]
Comment (ranquild) [reply frontend/src/metabase/ui/theme.ts:101]: Because later on we would need to pass additional parameters here, e.g. if/when we migrate to v7

**Comment by ranquild** [comment]
@uladzimirdev 2 - it's currently very hard to set the bottom margin on the last label before the input, so we add `marginTop` for inputs within `TextInput` (not all `Input`s). What's the issue with that?

**Comment by ranquild** [comment]
@uladzimirdev fixed 1 & 3

**Review by uladzimirdev — APPROVED** [review]

**Comment by ranquild** [comment]
@uladzimirdev I've merged other PRs here
- NumberInput has style changes only for the up/down control
- Other components have color/typography fixes

**Review by vbenedetti — APPROVED** [review]
Looks good to me. Thanks for fixing the issues found and discussed [here](https://metaboat.slack.com/archives/C057WD5L0JG/p1692976365177549). (x-referencing for visibility)
