### ISSUE TITLE
iframe resizer issue with require.ensure v0.27

### ISSUE THREAD

**Issue by itafras** [metabase/metabase#6361]
### Issue Description 

Embed dashboards and questions are not working with the 0.27 version for me.  I have tested in several environments it returns the following errors: 
```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (EmbedFrame.jsx:65)
    at EmbedFrame.componentWillMount (EmbedFrame.jsx:65)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:348)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
```
```
error TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:742)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:721)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:642)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:751)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:721)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:642)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
```

On Chrome I can not see my dashboard when I enter the publish page (blank), on Firefox I can't even access the last publishing page (for application embedding). 

The only way to bypass the issue for me was to remove the require.ensure in the code:
__From there__
  ```javascript
 componentWillMount() {
        if (window.iFrameResizer) {
            console.error("iFrameResizer resizer already defined.")
        } else {
            window.iFrameResizer = {
                autoResize: true,
                heightCalculationMethod: "bodyScroll",
                readyCallback: () => {
                    this.setState({ innerScroll: false })
                }
            }
            // $FlowFixMe: flow doesn't know about require.ensure
            require.ensure && require.ensure([], () => {
                require("iframe-resizer/js/iframeResizer.contentWindow.js")
            });
        }
    }
```
__To there__
```javascript
 componentWillMount() {
...
            // $FlowFixMe: flow doesn't know about require.ensure
                require("iframe-resizer/js/iframeResizer.contentWindow.js")
        }
    }
```

### Conditions
- On chrome Chrome 61.1 shows a blank page, on Firefox the button "Embed this question in an application" after clicking "sharing" in the dashboard is not working
- OS X 10
- Test with H2 and Postgres as metabase database
- Metabase version: 0.27
- Metabase hosting environment: Local & Elastic Beanstalk & Docker

- *Repeatable steps to reproduce the issue*
Download / git clone metajar
java -jar metabase.jar
Enable Sharing 
Create new question 
Share

**Comment by camsaul** [comment]
Duplicate of #6352
