### ISSUE TITLE
Scheduled notifications not being sent to email

### ISSUE THREAD

**Issue by rihadik** [metabase/metabase#66386]
### Describe the bug

After upgrading MB 0.50 to 0.57.4 scheduled notification emails stopped arriving, and some of the arrived ones have trouble displaying content although they do work for a little (30-40 minutes) after restarting MB, as shown by these lines in the log:

<img width="610" height="342" alt="Image" src="https://github.com/user-attachments/assets/a3bc2371-865f-4b93-8b72-45e1336d03ad" />

It's usually possible to send notifications manually, although those including graphs always fail.
Also, when restarting Metabase (java) when it stops sending notifications, SIGTERM doesn't suffice, you have to kill it with SIGKILL. Normally MB exits promptly with SIGTERM.

OS: FreeBSD 13.4
JDK: openjdk21-21.0.9+10.1

### Logs

```
2025-11-28 12:55:00,028 INFO notification.send :: Sending {mb-notification-id=268, mb-notification_id=268, mb-payload_type=:notification/card, mb-quartz-job-type=SendNotification, mb-subscription-id=268}
```

and then stop arriving until a further restart. Also this error is thrown periodically:

```
 2025-11-28 12:55:00,095 ERROR render.card :: Pulse card render error {mb-card_id=7301, mb-channel_type=:channel/email, mb-handler_id=271, mb-notification-id=270, mb-notification_id=270, mb-payload_type=:notification/card, mb-quartz-job-type=SendNotification, mb-subscription-id=270}
 java.lang.NoClassDefFoundError: Could not initialize class org.graalvm.polyglot.Engine$ImplHolder
       at org.graalvm.polyglot.Engine.getImpl(Engine.java:446)
...
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2",
      "clickhouse",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-11-26",
      "tag": "v0.57.4.2",
      "hash": "3446900"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.9+10-1",
    "java.vendor": "OpenJDK BSD Porting Team",
    "java.vendor.url": "https://github.com/battleblow/jdk21u/",
    "java.version": "21.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.9+10-1",
    "os.name": "FreeBSD",
    "os.version": "13.4-RELEASE-p1",
    "user.language": "en",
    "user.timezone": "Asia/Baku"
  }
}
```

### Severity

Critical

**Comment by rihadik** [comment]
How to repeat:

Case when scheduled report doesn't arrive:
1. Go to the dashboard containing the card (report)
2. Open the card
3. Click on "Move, trash, and more..."
4. Select "Create an alert"
5. Configure alert: choose any schedule and add email
6. Click Done
7. Wait for alert execution
8. No email is received

Case when to get a table report you click on Send email now:
1. Go to the dashboard containing the table report
2. Open the card
3. Click on "Move, trash, and more…"
4. Select "Create an alert"
5. Configure alert: choose any schedule and add email
6. Click "Send email now"
7. Email is received, but instead of table data, the email shows: "An error occurred while displaying this card."

Case when to get a chart report you click on Send email now:
1. Go to the dashboard containing the chart report
2. Open the card
3. Click on "Move, trash, and more…"
4. Select "Create an alert"
5. Configure alert: choose any schedule and add email
6. Click "Send email now"
7. Instead of receiving an email, Metabase shows: "Sending failed"

**Comment by rihadik** [comment]
One more thing I just noticed when restarting again to resume the sending:

`2025-11-30 21:23:25,085 INFO notification.send :: Gracefully shutting down notification dispatcher with 209 pending notifications to process {mb-dispatcher-count=2}
`

209 pending? It looks like the sending gets stuck on something? I tried setting `MB_NOTIFICATION_THREAD_POOL_SIZE` to 20 from the default 3, but it didn't help much.

**Comment by dwhitemv25** [comment]
I tried to reply to your post on the Discourse from a couple days ago, but you deleted it before I could finish.

```
"java.vendor": "OpenJDK BSD Porting Team",
 "os.name": "FreeBSD",
```

Notification emails that include dashboard contents require GraalVM. GraalVM is a binary blob component that is only supported on Windows and Linux. GraalVM is not supported on BSD OpenJDK.

You can install a Linux-compiled JDK (like Eclipse Temurin) and it works fine under modern FreeBSD versions with Linux compatibility enabled.

**Comment by rihadik** [comment]
> I tried to reply to your post on the Discourse from a couple days ago, but you deleted it before I could finish.

Sorry I thought the problem had been resolved when the messages started arriving after a restart.

**Comment by eliotmetabase** [comment]
@rihadik I noticed your post on Discourse where it seems like you may have found a solution.
Do you need additional support with this issue?

**Comment by rihadik** [comment]
@eliotmetabase not any more it seems, thanks. Perhaps it should be noted that for best results Metabase should run with Linux compatibility mode configured on BSDs.
