### ISSUE TITLE
Dashboard filters still broken after update to 0.29.2

### ISSUE THREAD

**Issue by ryan-tangocard** [metabase/metabase#7640]
Original issue: #7543 

Updated to 0.29.2 and I am still having issues with the filters on dashboards.

Still seeing the following error -
Uncaught TypeError: _this2._input.focus is not a function at ListSearchField.jsx:31

I also see this error when creating a custom question as soon as I hit Select a table.

Upon doing some additional testing, I am finding that if I keep my dashboard filter down to one tables questions it doesn't throw an error and works as expected. As soon as I add the filter to a question that is against another table with the same value it turns the filter back to the old look, throws the same error and will stop working after a few minutes. I have tried going through all of the tables and ensuring that the value is set to list, but it's still not working.

**Comment by mazameli** [comment]
Sorry you're still having problems, Ryan.

Just so I understand, is your situation that you have a dashboard with a filter which is connected to two separate questions which have separate, different fields that happen to share the same set of field values? E.g. they're both State fields (AK, AL, AZ, CA, CO, etc.), but one is called `Buyer State` and one is called `Seller State` or something like that? If that's the case, do the fields share the _exact_ same set of values?

**Comment by ryan-tangocard** [comment]
Yep. We have several questions that have a column called `Customer Success Manager`. 

I just looked at two questions that have this value to check to make sure they have the exact same set of values and it looks as though we do have a difference. One of the questions has one additional value available in the drop-down. 

Is this type of filtering not supported? In our current dashboard I am showing Revenue data and Case data and wanting to be able to filter on the CSM. There are going to be more situations where one data set and/or question won't have the exact same number of unique values (CSM, Sales Rep, Brand, etc).

**Comment by collegeimprovements** [comment]
We are facing similar kind of issue.

**Comment by buren** [comment]
I'm also seeing the above error as well as a few others, though at this point I can't even run any new query using the query-builder:

First error
```
initializeQb failed because of an error: DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at b64_to_utf8 (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/app-main.bundle.js?a148caa8cbdb77f1454b:14150:43)
    at b64url_to_utf8 (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/app-main.bundle.js?a148caa8cbdb77f1454b:14158:10)
    at deserializeCardFromUrl (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/app-main.bundle.js?a148caa8cbdb77f1454b:14141:21)
    at _callee2$ (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/app-main.bundle.js?a148caa8cbdb77f1454b:25813:72)
    at tryCatch (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/vendor.bundle.js?a148caa8cbdb77f1454b:118286:40)
    at Generator.invoke [as _invoke] (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/vendor.bundle.js?a148caa8cbdb77f1454b:118524:22)
    at Generator.prototype.(anonymous function) [as next] (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/vendor.bundle.js?a148caa8cbdb77f1454b:118338:21)
    at step (http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/app-main.bundle.js?a148caa8cbdb77f1454b:25611:191)
    at http://oddinsights.eu-central-1.elasticbeanstalk.com/app/dist/app-main.bundle.js?a148caa8cbdb77f1454b:25611:361
_callee2$ @ app-main.bundle.js:25885
blown_up
```

then the error posted in this thread

```
Uncaught TypeError: _this2._input.focus is not a function
    at app-main.bundle.js:34908
```

and finally

```
Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (Table.jsx:77)
    at getSetting (settings.js:207)
    at getSettings (settings.js:255)
    at app-main.bundle.js?a148caa8cbdb77f1454b:32907
    at index.js:76
    at index.js:36
    at index.js:90
    at index.js:36
    at Function.mapStateToProps [as mapToProps] (QueryHeader.jsx:43)
    at mapToPropsProxy (wrapMapToProps.js:43)
```

Not really sure what to do or how to proceed (maybe downgrade metabase?), let me know if I can do something.

**Comment by rcknr** [comment]
Having the same problem too. Fresh installation behaves like first gif above.

**Comment by ryan-tangocard** [comment]
@mazameli not sure if this is the right place to ask, but do you happen to know when this might get fixed? Most of our dashboards are broken due to this issue and I am losing momentum on Metabase with our internal users.

**Comment by tlrobinson** [comment]
FYI I think `_this2._input.focus` is a red herring and is not really related to the underlying issue. I've pushed a fix for that in #7904.

I think the real issue has to do with multiple different fields being mapped to the same parameter, which disables the `FieldValuesWidget`.

Are the fields you have mapped to the parameter the same underlying field via different foreign keys, or different fields entirely?

We should be able to support the former fairly easily.

**Comment by ryan-tangocard** [comment]
@tlrobinson Thanks for the reply.  To answer your question - I think I need to explain how I have things built on my end and where I think I need to go in order to support this filtering on multiple data sets -

I am creating several large denormalized tables that support different types of questions through Metabase -
Financials - transaction, customer and item data
Support Cases - customer and support case data
On-boarding - customer and on-boarding data

The key thing here is the customer information is the pointing at the same source data which I believed would allow me to filter on customer values to drill down on any of the above areas. What I am realizing is that since all the data is joined into one big data model there are instances where a customer can have transactions and no support cases which means the customer values between the two data sets isn't consistent. Based on this - I think I have two options for solving this issue -

1. Go through my denormalized tables and make sure I am starting from the customer and do a LEFT JOIN to the rest of my data to ensure all customer info is consistent between models - This would mean that questions would always need to contain some filter to exclude customers without the related transactions or support cases which shouldn't be a problem since we are almost always looking at a specific time period.

2. Separate customers from the denormalized tables and do a JOIN through Metabase. I haven't done a ton of testing on this, but would Metabase evaluate, read all values in the customer table to be used in filters regardless of what I join it with? Or would this be the same as the way I have everything currently?

Hope that makes sense.

**Comment by fatica** [comment]
We have this same problem.

Basically we have a series of denormalized tables that aggregate eCommerce sales data.  We have a product group that surfaces in nearly every such table.  

The moment we add a card to a dashboard who's question targets a second table, the dashboard filters turn from selections, to a free-form text entry (there is no autocomplete, or apparent ability to enter multiple values).

Basic steps to reproduce are 

1. Expose two different tables to metabase with a shared column name and the same values.
2.  Create a dashboard with a card exposing a question that reports on table A. 
3.  Establish a filter for the dashboard on the shared column name.  Notice you can choose from distinct values in the expected manner described in the documentation.
4.  Add a second card which exposes a question that reports on table B and connect the filter to the shared column name.
5.  Save the dashboard, refresh and observe that the dashboard filter no longer includes the ability to select from the drop-downs.

For us this forces us to create a large number of disconnected dashboards, which confuses users and makes inter-relations, correlations etc very difficult due to the constant dashboard switching.

**Comment by LionelBino** [comment]
I Have the same problem, when in the category i have a null value [See video](https://vimeo.com/310181115)

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
