### ISSUE TITLE
Failed to connect to sparksql after upgrading metabase to v50.31

### ISSUE THREAD

**Issue by guicailiao** [metabase/metabase#49331]
### Describe the bug

After upgrading metabase from v0.47.13(v0.47.13 -> v0.48.13 -> v0.49.25 -> v0.50.31) to v0.50.31, we can no longer query data through sparksql from metabase. 

### To Reproduce

1. running metabase with docker image(metabase:metabase:v0.50.3)
2. adding datasource through sparksql.(should failed here)

### Logs

logs from metabase server:

```
2024-10-30 09:14:25,509 ERROR driver.util :: Failed to connect to Database
java.lang.NoSuchMethodError: 'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)'
	at org.apache.hive.jdbc.HiveConnection.createHttpTransport(HiveConnection.java:372)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:341)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:228)
	at metabase.driver.hive_like.fixed_hive_connection.proxy$org.apache.hive.jdbc.HiveConnection$ff19274a.<init>(Unknown Source)
	at metabase.driver.hive_like.fixed_hive_connection$fixed_hive_connection.invokeStatic(fixed_hive_connection.clj:9)
	at metabase.driver.hive_like.fixed_hive_connection$fixed_hive_connection.invoke(fixed_hive_connection.clj:9)
	at metabase.driver.sparksql.SparkSQLDataSource.getConnection(sparksql.clj:95)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:348)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:345)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__82691.invoke(connection.clj:357)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__82673.invoke(connection.clj:333)
	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)
	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:328)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:324)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:356)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:352)
	at metabase.driver.sql_jdbc$fn__108827.invokeStatic(sql_jdbc.clj:49)
	at metabase.driver.sql_jdbc$fn__108827.invoke(sql_jdbc.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__56580.invoke(util.clj:167)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Information about your Metabase installation

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres",
      "sparksql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-22",
      "tag": "v0.50.31",
      "hash": "f754eda"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.18"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.4.0-45-ponyai",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

 blocking an upgrade

**Comment by guicailiao** [comment]
A simple way of reproduce.

1. start container: 
```
docker run -d -p 3000:3000 --name metabase nexus.corp.pony.ai:5000/metabase/metabase:v0.50.31
```
2. access metabase http://localhost:3000
3. add spark datasource would fail.

![Image](https://github.com/user-attachments/assets/9d8eea70-2803-49c7-9d62-d18b085c93a4)

Note: Tried `docker run -d -p 3000:3000 --name metabase nexus.corp.pony.ai:5000/metabase/metabase:v0.47.13` and it works. `v0.51.1` also not working.

**Comment by paoliniluis** [comment]
duplicate of https://github.com/metabase/metabase/issues/46793
