### PR TITLE
Query compilation error rate and performance testing

### PR DESCRIPTION
**Pull request by rileythomp**
Closes [QUE2-483](https://linear.app/metabase/issue/QUE2-483/build-out-tooling-to-check-query-compilation-error-rate-and)

### Description

Builds upon the `metadata-for` and `compile-card` functions introduced in https://github.com/metabase/metabase/pull/67952. 

Use `generate-card-compilation-analysis` to generate a csv file with the query compilation results for a list of card ids. This csv will be uploaded to your local metabase instance to allow for analysis of the results. 

For example, you can generate two csvs from two branches, and then run the example query to see if there was any meaning change in query compilation error rates or time. 

For the comparison of results between master and the [column keys PR](https://github.com/metabase/metabase/pull/68297), see [these sheets](https://docs.google.com/spreadsheets/d/16lQWeBsxnCmSq5rSH-nktw3r8XahHDq6U4_THr1Q2Ug/edit?gid=105956422#gid=105956422). 

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: dev/src/dev/debug_qp/analyze_user_query.clj [hunk 1]
```diff
@@ -146,6 +152,63 @@
...
+                             (let [mp (metadata-for my-ctx {:card [card-id]})
+                                   elapsed-ms (compile-card-time mp card-id)
+                                   card-num (inc idx)
+                                   card-pct (-> card-num (/ num-cards) (* 100) double)]
+                               (when (= 0 (mod card-num 10))
+                                 (tap> (format "Processed %.0f%% of %d cards"  card-pct num-cards)))
+                               [card-id {:compilation_time elapsed-ms :error_msg ""}])
+                             (catch Throwable t
+                               (tap> (format "Error on card %d: %s" card-id (.getMessage t)))
+                               [card-id {:compilation_time 0.0 :error_msg (.getMessage t)}]))))
```
Comment (metamben) [inline dev/src/dev/debug_qp/analyze_user_query.clj:185]: can't we set `:compilation_time` to `nil`?

File: dev/src/dev/debug_qp/analyze_user_query.clj [hunk 2]
```diff
@@ -146,6 +152,63 @@
...
+        _ (tap> (format "Finished processing %d cards" num-cards))
+        cols (-> card-stats vals first keys)
```
Comment (metamben) [inline dev/src/dev/debug_qp/analyze_user_query.clj:187]:
```suggestion
        cols (-> card-stats first val keys)
```

File: dev/src/dev/debug_qp/analyze_user_query.clj [hunk 3]
```diff
@@ -146,6 +152,63 @@
...
+        header (into ["card_id"] (map name cols))
+        rows (for [[card-id stats] card-stats]
+               (into [(str card-id)]
+                     (map #(str (get stats %)) cols)))]
```
Comment (metamben) [inline dev/src/dev/debug_qp/analyze_user_query.clj:191]: - are these explicit `str` calls really needed?
- I would use `(apply juxt cols)` to create a function I can call on `stats`.
- I would use the 3 arity form of `into`.

**Review by metamben — APPROVED** [review]
