### ISSUE TITLE
Compilation error occurred in v0.48.1

### ISSUE THREAD

**Issue by cverdela** [metabase/metabase#37212]
### Describe the bug

Compilation exception occurred in v0.48.1. After downloading the source code and installing dependencies, an error occurred during execution. The error message is: Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:581). com.unboundid.ldap.sdk.LDAPResult. However, I could successfully compile with the same operations on v0.48.0.

### To Reproduce

clojure -M:run

### Logs

{:clojure.main/message
 "Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:581).\r\ncom.unboundid.ldap.sdk.LDAPResult\r\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.ClassNotFoundException,
  :clojure.error/line 581,
  :clojure.error/cause "com.unboundid.ldap.sdk.LDAPResult",
  :clojure.error/symbol jdk.internal.loader.BuiltinClassLoader/loadClass,
  :clojure.error/source "BuiltinClassLoader.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error macroexpanding at (metabase/integrations/ldap.clj:1:1).",
    :data
    {:clojure.error/phase :execution,
     :clojure.error/line 1,
     :clojure.error/column 1,
     :clojure.error/source "metabase/integrations/ldap.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7665]}
   {:type java.lang.ExceptionInInitializerError, :at [java.lang.Class forName0 "Class.java" -2]}
   {:type java.lang.ClassNotFoundException,
    :message "com.unboundid.ldap.sdk.LDAPResult",
    :at [jdk.internal.loader.BuiltinClassLoader loadClass "BuiltinClassLoader.java" 581]}],
  :trace

### Information about your Metabase installation

```JSON
none
```

### Severity

can not develop
